### ISSUE TITLE
No such file or directory: 'markdownserver/resources/css/github.css'

### ISSUE THREAD

**Issue by amitu** [ohbarye/markdown-server#1]
After a fresh install.

markdown-server==0.1.1
Python 2.7.11

```python
Traceback (most recent call last):
  File "/Users/amitu/.pyenv/versions/home/bin/mdsvr", line 7, in <module>
    from markdownserver import main
  File "/Users/amitu/.pyenv/versions/home/lib/python2.7/site-packages/markdownserver/__init__.py", line 5, in <module>
    converter = MarkdownConverter()
  File "/Users/amitu/.pyenv/versions/home/lib/python2.7/site-packages/markdownserver/markdown_converter.py", line 9, in __init__
    css = codecs.open(css_root + css_name,encoding=ms_encoding,mode='r')
  File "/Users/amitu/.pyenv/versions/home/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'markdownserver/resources/css/github.css'
```

**Comment by ohbarye** [comment]
Ah, I assume that I'm dealing in those paths with wrong way... 
I will investigate.

**Comment by ohbarye** [comment]
@amitu 
I fixed the bug and released `0.1.3`.
Now, I think it would work well with the following command. (I confirmed only on my end, though.)

```
$ pip install markdown-server
$ markdownserver
$ open http://localhost:8009/sample.md
```

I'm very sorry for my late reply, but I truly appreciate you that you created this issue!

**Comment by amitu** [comment]
Thanks for the release. 

Not fixed :-(

```python
Traceback (most recent call last):
  File "/Users/amitu/.pyenv/versions/2.7.11/envs/burstic/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/amitu/.pyenv/versions/2.7.11/envs/burstic/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/amitu/.pyenv/versions/2.7.11/envs/burstic/lib/python2.7/site-packages/markdownserver/__init__.py", line 11, in gfmize
    html_file_name = os.path.basename(converter.convert(resource))
  File "/Users/amitu/.pyenv/versions/2.7.11/envs/burstic/lib/python2.7/site-packages/markdownserver/markdown_converter.py", line 31, in convert
    code = md.markdown(self.read_md(src), extensions=[markdown_type])
  File "/Users/amitu/.pyenv/versions/2.7.11/envs/burstic/lib/python2.7/site-packages/markdownserver/markdown_converter.py", line 35, in read_md
    md_file = codecs.open(os.path.join(markdown_dir, file_name),encoding=ms_encoding,mode='r')
  File "/Users/amitu/.pyenv/versions/2.7.11/envs/burstic/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/Users/amitu/.pyenv/versions/2.7.11/envs/burstic/lib/python2.7/site-packages/markdownserver/resources/markdown/foo.md'
`

**Comment by ohbarye** [comment]
Does your markdown file which you want to convert locate the following path?

`'/Users/amitu/.pyenv/versions/2.7.11/envs/burstic/lib/python2.7/site-packages/markdownserver/resources/markdown/foo.md'`

**Comment by amitu** [comment]
No. Its in current folder, ~/projects/burstic/foo.md.
