### ISSUE TITLE
ImportError: No module named 'md_to_html'

### ISSUE THREAD

**Issue by hudsantos** [ohbarye/markdown-server#10]
Just have followed this instruction here: https://pypi.org/project/markdown-server/

But not using python 2.7...
Trying with python 3.5 instead:

```
user@localhost /tmp $ git clone https://github.com/ohbarye/markdown-server
Cloning into 'markdown-server'...
remote: Enumerating objects: 108, done.
remote: Total 108 (delta 0), reused 0 (delta 0), pack-reused 108
Receiving objects: 100% (108/108), 24.30 KiB | 0 bytes/s, done.
Resolving deltas: 100% (49/49), done.
Checking connectivity... done.
user@localhost /tmp $ cd markdown-server/
user@localhost /tmp/markdown-server $ virtualenv -p /usr/bin/python3.5 .venv
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /tmp/markdown-server/.venv/bin/python3.5
Also creating executable in /tmp/markdown-server/.venv/bin/python
Installing setuptools, pip, wheel...
done.

user@localhost /tmp/markdown-server $ source .venv/bin/activate
(.venv) user@localhost /tmp/markdown-server $ pip install -r requirements.txt
Collecting bottle==0.12.8 (from -r requirements.txt (line 1))
Collecting linecache2==1.0.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c7/a3/c5da2a44c85bfbb6eebcfc1dde24933f8704441b98fdde6528f4831757a6/linecache2-1.0.0-py2.py3-none-any.whl
Collecting Markdown==2.6.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/59/bf/6bce4d6d91d25eaa58d8e88d8994b2b603ed1b223b25a92f68c3fd0e8fd9/Markdown-2.6.2-py2.py3-none-any.whl
Obtaining markdownserver-master from git+https://github.com/ohbarye/markdown-server@f85a63ba06ca7cb5beb59bd96153d7ba1fa867ae#egg=markdownserver-master (from -r requirements.txt (line 4))
  Cloning https://github.com/ohbarye/markdown-server (to revision f85a63ba06ca7cb5beb59bd96153d7ba1fa867ae) to ./.venv/src/markdownserver-master
  Running command git clone -q https://github.com/ohbarye/markdown-server /tmp/markdown-server/.venv/src/markdownserver-master
  Running command git checkout -q f85a63ba06ca7cb5beb59bd96153d7ba1fa867ae
  WARNING: Generating metadata for package markdownserver-master produced metadata for project name markdownserver. Fix your #egg=markdownserver-master fragments.
Collecting py-gfm==0.1.0 (from -r requirements.txt (line 5))
Collecting Pygments==2.0.2 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/87/e3/cadb43a197476ec0adef73292ea7ea188f2b0531188eebc150905d3ed78c/Pygments-2.0.2-py3-none-any.whl
Collecting six==1.9.0 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/10/e3/a7f8eea80a9fa8358c1cd89ef489bc03675e69e54ed2982cd6f2a28d8295/six-1.9.0-py2.py3-none-any.whl
Collecting traceback2==1.4.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/17/0a/6ac05a3723017a967193456a2efa0aa9ac4b51456891af1e2353bb9de21e/traceback2-1.4.0-py2.py3-none-any.whl
Collecting unittest2==1.0.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/e3/f0/cb7c6303f03509045e1ec167db2b5a01d36bb616d710e895038bdb509fff/unittest2-1.0.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.venv/lib/python3.5/site-packages (from py-gfm==0.1.0->-r requirements.txt (line 5)) (41.0.1)
Collecting argparse (from unittest2==1.0.1->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Installing collected packages: bottle, linecache2, Markdown, Pygments, traceback2, six, argparse, unittest2, py-gfm, markdownserver
  Running setup.py develop for markdownserver
Successfully installed Markdown-2.6.2 Pygments-2.0.2 argparse-1.4.0 bottle-0.12.8 linecache2-1.0.0 markdownserver py-gfm-0.1.0 six-1.9.0 traceback2-1.4.0 unittest2-1.0.1

(.venv) user@localhost /tmp/markdown-server $ markdownserver
Traceback (most recent call last):
  File "/tmp/markdown-server/.venv/bin/markdownserver", line 11, in <module>
    load_entry_point('markdownserver', 'console_scripts', 'markdownserver')()
  File "/tmp/markdown-server/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/markdown-server/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/tmp/markdown-server/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/tmp/markdown-server/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/markdown-server/.venv/src/markdownserver-master/markdownserver/__init__.py", line 2, in <module>
    from md_to_html import MarkdownConverter
ImportError: No module named 'md_to_html'
(.venv) user@localhost /tmp/markdown-server $
```

How could we port it to python3.5?

**Comment by ohbarye** [comment]
Thanks for trying markdown-server. I'm afraid to say, as I no longer use this tool and I'm no longer a pythonista, I have no idea. 🙏

**Comment by FreetechAdmin** [comment]
Use
```
export PYTHONPATH='.'
```
